### PR TITLE
Upgrade tools and libraries

### PR DESCRIPTION
**Pull request by FooBarWidget**
autoconf 2.69 -> 2.70
automake 1.16.1 -> 1.16.3
ccache 3.5 -> 3.7.12
CMake 3.16.4 -> 3.19.3
OpenSSL 1.0.2q -> 1.0.2u
curl 7.63.0 -> 7.74.0
Git 2.25.1 -> 2.30.0
SQLite 2018-3260000 -> 2020-3340000

### CODE REVIEW

**Comment by nightlark** [comment]
Can OpenSSL get updated to `1.1.1i`?

**Comment by FooBarWidget** [comment]
OpenSSL 1.1 has API incompatibilities with 1.0. I'd rather defer that upgrade to the next major version of Holy Build Box, in which we upgrade to CentOS 7 as well.

**Comment by nightlark** [comment]
Okay, I see that 1.0.2 is still getting security fixes. Is 1.0.2x available (https://www.openssl.org/news/vulnerabilities-1.0.2.html)?

**Comment by FooBarWidget** [comment]
1.0.2x only has a proper release for premium support customers.

It's clear we can't stay on 1.0.2. My suggestion to upgrade to 1.0.2u is just for the interim. We'll have to upgrade to 1.1 (and bump Holy Build Box's major version number) any some point soon.

**Review by nightlark — APPROVED** [review]

**Pull request merged**
